# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c2ed71b5bc502d8cc1faf14f55ae6e2db8ef7efae434bd1d5e3e8db4cce655fe75eb511b4a1a1bd506fc85c66537e10a48567a2e0c0b379334930c563f5e084

test:
  secret_key_base: ae0779751cae223a016c0b766307ea665e593afc27ae833ed1935ba39ecf79f8bb4ef7a82f5b02a47ec55c7099b384b3b5ae07f7bb4466f7c6dcd354019be8f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
